# Ansible inventory created from ['/home/ansible/netlab/topology.yml', 'package:topology-defaults.yml']
#

ansible_become: true
ansible_become_method: enable
ansible_connection: network_cli
ansible_network_os: eos
ansible_ssh_pass: admin
ansible_user: admin
features:
  bfd: {}
  bgp:
    activate_af: true
    community:
      2octet:
      - standard
      extended:
      - extended
      large:
      - large
      standard:
      - standard
      - large
    import:
    - ospf
    - isis
    - ripv2
    - connected
    - vrf
    ipv6_lla: true
    local_as: true
    local_as_ibgp: true
    vrf_local_as: true
  dhcp:
    client:
      ipv4: true
    relay: true
    server: true
    vrf: true
  evpn:
    asymmetrical_irb: true
    bundle:
    - vlan_aware
    irb: true
  gateway:
    protocol:
    - anycast
    - vrrp
  initial:
    ipv4:
      unnumbered: true
    ipv6:
      lla: true
    max_mtu: 9194
    min_mtu: 68
    system_mtu: true
  isis:
    import:
    - bgp
    - ospf
    - ripv2
    - connected
    - vrf
    unnumbered:
      ipv4: true
      ipv6: true
      network: true
  lag:
    mlag:
      peer:
        ifindex: 4094
        ip: 169.254.127.0/31
        vlan: 4094
    passive: true
  mpls:
    6pe: true
    bgp: true
    ldp: true
    vpn: true
  ospf:
    default:
      policy: true
    import:
    - bgp
    - isis
    - ripv2
    - connected
    - vrf
    password: true
    priority: true
    timers: true
    unnumbered: true
  ripv2:
    ipv4: true
    ipv6: false
    passive: false
  routing:
    aspath: true
    community:
      expanded: true
    policy:
      match:
      - prefix
      - nexthop
      - aspath
      - community
      set:
      - locpref
      - med
      - weight
      - prepend
      - community
    prefix: true
    static:
      inter_vrf: true
      vrf: true
  sr: {}
  stp:
    enable_per_port: true
    port_type: true
    supported_protocols:
    - stp
    - rstp
    - mstp
    - pvrst
  vlan:
    model: l3-switch
    native_routed: true
    subif_name: '{ifname}.{subif_index}'
    svi_interface_name: Vlan{vlan}
  vrf:
    bgp: true
    isis: true
    ospfv2: true
    ospfv3: true
  vxlan: {}
